version: "3.9"
name: dinosearch
services:
  db:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
    networks:
      - dinonet
  crawler:
    build:
      context: .
      target: runner
    depends_on:
      - db
    networks:
      - dinonet
    env_file:
      - .env.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M

volumes:
  data:

networks:
  dinonet:
    driver: bridge
